#!/usr/bin/env bash

SUBDCLOUD="" #ex. "cloud"
SUBDWWW="" #ex. "www"
DOMAINTLD="" #ex. "yourdomain\.tld"
EMAIL="" #ex. "your@email.tld"
TYPE=""
FROM_FILE=""
while getopts c:w:d:e:t:h option
do
case "${option}"
in
c) SUBDCLOUD=${OPTARG//\./\\\.};;
w) SUBDWWW=${OPTARG//\.//\\\.};;
d) DOMAINTLD=${OPTARG//\./\\\.};;
e) EMAIL=${OPTARG//\./\\\.};;
t) TYPE=${OPTARG//\./\\\\.};;
h) echo "Usage: ./setup -d example.com -e me@example.com [-c mycloud] [-w www] [-t type]"
	echo "-d Domain for the site"
	echo "-e Email address used for Lets Encrypt"
	echo "-c Cloud subdomain"
	echo "-w WWW subdomain"
	echo "-t type of installation"
   exit;;
esac
done

if [ -z "$TYPE" ]; then
	echo "No type given, assuming nextcloud only"
	TYPE="nextcloud"
fi

if [ -z "$SUBDCLOUD" ]; then
        echo "No cloud subdomain given, assuming cloud."
	SUBDCLOUD="cloud"
fi

if [ -z "$SUBDWWW" ]; then
        echo "No www subdomain given, assuming www."
	SUBDWWW="www"
fi

if [ -z "$DOMAINTLD" ]; then
        echo "No domain given, aborting."
	exit
fi

if [ -z "$EMAIL" ]; then
        echo "No contact address given, aborting."
	exit
fi

case "$TYPE"
in
grav) 
	FROM_FILE="docker-compose-grav.yml"
	;;
nextcloud) 
	FROM_FILE="docker-compose-nextcloud-only.yml"
	;;
gatsby) 
	FROM_FILE="docker-compose-gatsby.yml"
	;;
esac

cp $FROM_FILE docker-compose.yml
mv fpmcron/nextcloud.example.com fpmcron/$SUBDCLOUD.${DOMAINTLD//\\\./\.}
mv fpmcron/nextcloud.example.com_location fpmcron/$SUBDCLOUD.${DOMAINTLD//\\\./\.}\_location
find . -path ./.git -prune -o -type f -print | grep -vE "README|setup" | xargs sed -i "s/nextcloud\.example\.com/$SUBDCLOUD\.$DOMAINTLD/g"
find . -path ./.git -prune -o -type f -print | grep -vE "README|setup" | xargs sed -i "s/www\.example\.com/$SUBDWWW\.$DOMAINTLD/g"
find . -path ./.git -prune -o -type f -print | grep -vE "README|setup" | xargs sed -i "s/me@example\.com/$EMAIL/g"
find . -path ./.git -prune -o -type f -print | grep -vE "README|setup" | xargs sed -i "s/example\.com/$DOMAINTLD/g"

